export const PROJECTS = [
	{
		id: 0,
		title: 'eCommerce Medusajs',
		description: 'La Fuerza del Alma eCommerce',
		image: [
			'/images/ecommerce.webp',
			'/images/ecommerce2.webp',
			'/images/ecommerce3.webp',
		],
		web: 'https://www.lafuerzadelalma.com/',
		github: 'https://github.com/lfdadev?tab=repositories',
	},
	{
		id: 1,
		title: 'Static website React',
		description: 'Puzzle Madriz restaurant',
		image: [
			'/images/puzzle.webp',
			'/images/puzzle2.webp',
			'/images/puzzle3.webp',
		],
		web: 'https://puzzlemadriz.com/',
		github: 'https://github.com/davidFCDev/restaurant-react',
	},
	{
		id: 2,
		title: 'Landing page Figma',
		description: 'Replicated web from figma',
		image: [
			'/images/landing-figma.webp',
			'/images/landing-figma2.webp',
			'/images/landing-figma3.webp',
		],
		web: 'https://landing-figma-huba.netlify.app/',
		github: 'https://github.com/davidFCDev/landing-page-figma',
	},
	{
		id: 3,
		title: 'Landing page Crypto Lockpay',
		description: 'Website for crypto locker',
		image: [
			'/images/lockpay.webp',
			'/images/lockpay2.webp',
			'/images/lockpay3.webp',
		],
		web: 'https://landing-crypto-figma.netlify.app/',
		github: 'https://github.com/davidFCDev/figma-crypto-clone',
	},
	{
		id: 4,
		title: 'Figma clone university',
		description: 'Website for universities search',
		image: [
			'/images/schools.webp',
			'/images/schools2.webp',
			'/images/schools3.webp',
		],
		web: 'https://figma-university.netlify.app/',
		github: 'https://github.com/davidFCDev/figma-schools-page',
	},
	{
		id: 5,
		title: 'Landing page Crypto',
		description: 'Website for crypto currency',
		image: [
			'/images/basecola.webp',
			'/images/basecola2.webp',
			'/images/basecola3.webp',
		],
		web: 'https://basecola.com/',
		github: 'https://github.com/davidFCDev/base-cola',
	},
	{
		id: 6,
		title: 'Forum R&M React',
		description: 'Context, api, authentication, CRUD...',
		image: ['/images/foro.webp', '/images/foro2.webp', '/images/foro3.webp'],
		web: 'https://fororickymorty.netlify.app/',
		github: 'https://github.com/davidFCDev/foro-reactjs',
	},
	{
		id: 7,
		title: 'Macros project React',
		description: 'Macronutrients calculator app. No responsive. api_key needed',
		image: [
			'/images/macros2.webp',
			'/images/macros.webp',
			'/images/macros3.webp',
		],
		web: 'https://macrofit.netlify.app/',
		github: 'https://github.com/davidFCDev/macrofit-react-app',
	},
	{
		id: 8,
		title: 'Tech test on React',
		description: 'React-router, redux. TheMOVIEdb api',
		image: [
			'/images/prueba-tecnica.webp',
			'/images/prueba-tecnica2.webp',
			'/images/prueba-tecnica3.webp',
		],
		web: 'https://prueba-reactjs.netlify.app/',
		github: 'https://github.com/davidFCDev/Prueba-tecnica',
	},
	{
		id: 9,
		title: 'Project React',
		description: 'Netflix clone with TheMOVIEdb api',
		image: [
			'/images/tenflix.webp',
			'/images/tenflix2.webp',
			'/images/tenflix3.webp',
		],
		web: 'https://tenflix-react.netlify.app/',
		github: 'https://github.com/davidFCDev/tenflix-api-react',
	},
	{
		id: 10,
		title: 'Random project React',
		description: 'PS5 menu with animations',
		image: ['/images/ps5.webp', '/images/ps52.webp', '/images/ps53.webp'],
		web: 'https://menu-ps5.netlify.app/',
		github: 'https://github.com/davidFCDev/menu-ps5-react',
	},
	{
		id: 11,
		title: 'Sport site React',
		description: 'Sport website ready to use',
		image: [
			'/images/deportiva.webp',
			'/images/deportiva2.webp',
			'/images/deportiva3.webp',
		],
		web: 'https://sport-web.netlify.app/',
		github: 'https://github.com/davidFCDev/sport-web-react',
	},
];
