export const PROYECTS = [
	{
		id: 1,
		title: 'Landing page Crypto',
		description: 'Web crypto con React',
		image: '/images/basecola.webp',
		web: 'https://basecola.com/',
		github: 'https://github.com/davidFCDev/base-cola',
	},
	{
		id: 2,
		title: 'Landing page Figma',
		description: 'Replicated web from figma',
		image: '/images/landing-figma.webp',
		web: 'https://landing-figma-huba.netlify.app/',
		github: 'https://github.com/davidFCDev/landing-page-figma',
	},
	{
		id: 3,
		title: 'Foro R&M React',
		description: 'Context, api, authentication, CRUD...',
		image: '/images/foro.webp',
		web: 'https://fororickymorty.netlify.app/',
		github: 'https://github.com/davidFCDev/foro-reactjs',
	},
	{
		id: 4,
		title: 'Página web React',
		description: 'Restaurante Puzzle Madriz',
		image: '/images/puzzle.webp',
		web: 'https://puzzlemadriz.com/',
		github: 'https://github.com/davidFCDev/restaurant-react',
	},
	{
		id: 5,
		title: 'Proyecto macros React',
		description: 'Aplicación de macros e ingredientes. No responsive. Necesita api_key',
		image: '/images/macros.webp',
		web: 'https://macrofit.netlify.app/',
		github: 'https://github.com/davidFCDev/macrofit-react-app',
	},
	{
		id: 6,
		title: '',
		description: '',
		image: '',
		web: '',
		github: '',
	},
	{
		id: 7,
		title: '',
		description: '',
		image: '',
		web: '',
		github: '',
	},
	{
		id: 8,
		title: '',
		description: '',
		image: '',
		web: '',
		github: '',
	},
	{
		id: 9,
		title: '',
		description: '',
		image: '',
		web: '',
		github: '',
	},
];
